### PR TITLE
Able to set digits precision

### PR DESCRIPTION
**Pull request by marciz**

### CODE REVIEW

**Comment by Swechhya** [comment]
@marciz  Could you please explain what this PR is handling?

**Comment by marciz** [comment]
jsonlite::toJSON default is 4 digits for numeric
I think there is an issue if we want to use more than 4 digits to inputs
`excelTable(data = data.frame(a = 0.123456789))$x$data`
>[[0.1235]]

**Comment by Swechhya** [comment]
@marciz , doesn't your `mask` attribute in your #45 handle the same thing?

**Comment by marciz** [comment]
Yes, it handles jexcel inputs. But I guess this line
https://github.com/Swechhya/excelR/blob/a9fdb9b03d03a7d984feaa31af1a7fb081fb3e7b/R/jexcel.R#L110
trims any extra digits above 4
> jsonlite::toJSON(1/3)
[0.3333]

**Comment by marciz** [comment]
Or probably just set 
`paramList$data <- jsonlite::toJSON(data, dataframe = "values", na = "null", digits = NA) `
to avoid extra new parameters. It just wont be compatibility with current excelR version, if using >4 digits for input

**Comment by Swechhya** [comment]
@marciz, This is a good feature to set digit precision. Merged this. Thanks for the PR 🙂.

**Pull request merged**
