### PR TITLE
add updateTable

### PR DESCRIPTION
**Pull request by marciz**
Example from https://bossanova.uk/jexcel/v3/examples/table-style
Note that numeral.js is missing, could probably add it
```
data <- jsonlite::fromJSON(
  gsub("'", '"', "[
    ['BR', 'Cheese', 1, 3.99],
    ['CA', 'Apples', 0, 1.00],
    ['US', 'Carrots', 1, 0.90],
    ['GB', 'Oranges', 0, 1.20],
    ['CH', 'Chocolats', 1, 0.40],
    ['AR', 'Apples', 1, 1.10],
    ['AR', 'Bananas', 1, 0.30],
    ['BR', 'Oranges', 1, 0.95],
    ['BR', 'Pears', 1, 0.90],
    ['', '', '', '=ROUND(SUM(D1:D8), 2)']
]"))

columns <- jsonlite::fromJSON(
  gsub("(\\w+):", "\"\\1\":", 
       gsub("'", '"', "[
        { type: 'autocomplete', title:'Country', width:'250', url:'/jexcel/countries' },
        { type: 'autocomplete', title:'Food', width:'150', source:['Apples','Bananas','Carrots','Oranges','Cheese','Kiwi','Chocolats','Pears'] },
        { type: 'checkbox', title:'Stock', width:'100' },
        { type: 'number', title:'Price', width:'100' }
    ]")))

# no url option in excelTable param columns
columns$source[1] <- list(jsonlite::fromJSON(paste0('https://bossanova.uk', columns$url[1])))
columns$url <- NULL

updateTable <- "function(instance, cell, col, row, val, label, cellName) {
        // Number formating
        if (col == 3) {
            // Get text
            txt = cell.innerText;
            // Format text
            
              // no numeral
              //txt = numeral(txt).format('0,0.00');
              
            // Update cell value
            cell.innerHTML = '$ ' + txt;
        }

        // Odd row colours
        if (row % 2) {
            cell.style.backgroundColor = '#edf3ff';
        }

        // Total row
        if (row == 9) {
            if (col < 3) {
                cell.innerHTML = '';
            } 

            if (col == 2) {
                cell.innerHTML = 'Total';
                cell.style.fontWeight = 'bold';
            }

            cell.className = '';
            cell.style.backgroundColor = '#f46e42';
            cell.style.color = '#ffffff';
        }
    }"

excelR::excelTable(data = data, columns = columns, updateTable = updateTable)
```
`

### CODE REVIEW

**Comment by Swechhya** [comment]
@marciz , don't you think using a custom `JS` function will be a hard think for an `R` users without any `JS` background?

**Comment by Swechhya** [comment]
@marciz , don't you think using a custom `JS` function will be a hard think for an `R` users without any `JS` background?

**Comment by marciz** [comment]
I think it will, but at least the is an option for those who know some JS. 
For rhandsontable there is a similar option - https://github.com/jrowen/rhandsontable/blob/639b0a511b216391df44c45ea7ef8c934269c28a/R/rhandsontable.R#L406
Also this option could help to create heatmap for excelR in a similar way as in rhandsontable

Probably even better option would be to add dots `...` parameter in excelTable function, which would allow to define all other jexcel parameters not currently mentioned in excelTable

**Comment by Swechhya** [comment]
@marciz, then maybe adding dots `...` would be better then explicitly specifying `updateTable` parameter. What do you think?

**Comment by marciz** [comment]
Agree, dots would be more flexible. updateTable can be mentioned in examples

**Comment by Swechhya** [comment]
As your [PR](https://github.com/Swechhya/excelR/pull/41) resolves this feature, closing this PR.

**Pull request closed without merging**
